# Generated by Django 5.1.7 on 2025-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_archetype_background_skill_character_creation_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='default_modifier',
            field=models.IntegerField(default=-1),
        ),
    ]
