# Generated by Django 5.1.7 on 2025-03-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_skill_default_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.IntegerField()),
                ('modifier_type', models.CharField(choices=[('ATTRIBUTE', 'Attribute'), ('SKILL', 'Skill')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
