# Generated by Django 5.1.7 on 2025-03-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(choices=[('acquaintance', 'Acquaintance'), ('friend', 'Friend')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='characters.character')),
            ],
        ),
    ]
