# Generated by Django 5.1.7 on 2025-03-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('COMMON', 'Common'), ('MAGICAL', 'Magical')], default='COMMON', max_length=20)),
                ('multi_allowed', models.BooleanField(default=False)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('effect_data', models.JSONField(blank=True, null=True)),
                ('usage_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='archetypes',
        ),
        migrations.CreateModel(
            name='CharacterEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('usage_data', models.JSONField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_edges', to='characters.character')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_edges', to='characters.edge')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='edges',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.edge'),
        ),
        migrations.DeleteModel(
            name='Archetype',
        ),
    ]
