# Generated by Django 5.1.7 on 2025-03-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_edge_remove_character_archetypes_characteredge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='edges',
            new_name='edge',
        ),
    ]
