# Generated by Django 5.1.7 on 2025-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_rename_edges_character_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
