# Generated by Django 5.1.7 on 2025-03-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_edge_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('category', models.CharField(default='COMMON', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('max_level', models.PositiveSmallIntegerField(default=2)),
                ('multi_allowed', models.BooleanField(default=False)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('usage_notes', models.TextField(blank=True)),
                ('levels', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
