# Generated by Django 5.1.7 on 2025-03-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_characterfocus_character_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.CreateModel(
            name='CharacterVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.PositiveIntegerField(default=0)),
                ('max_hp', models.PositiveIntegerField(default=0)),
                ('attack_bonus_base', models.IntegerField(default=0)),
                ('base_ac', models.IntegerField(default=0)),
                ('save_physical', models.IntegerField(default=0)),
                ('save_evasion', models.IntegerField(default=0)),
                ('save_mental', models.IntegerField(default=0)),
                ('save_luck', models.IntegerField(default=0)),
                ('is_frail', models.BooleanField(default=False)),
                ('is_mortally_wounded', models.BooleanField(default=False)),
                ('strength', models.PositiveIntegerField(default=10)),
                ('dexterity', models.PositiveIntegerField(default=10)),
                ('constitution', models.PositiveIntegerField(default=10)),
                ('intelligence', models.PositiveIntegerField(default=10)),
                ('wisdom', models.PositiveIntegerField(default=10)),
                ('charisma', models.PositiveIntegerField(default=10)),
                ('system_strain_current', models.IntegerField(default=0)),
                ('system_strain_max', models.IntegerField(default=0)),
                ('trauma_target', models.IntegerField(default=6)),
                ('major_injuries', models.JSONField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='characters.character')),
            ],
        ),
    ]
