# Generated by Django 5.1.7 on 2025-03-28 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_remove_character_charisma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_identifier', models.CharField(help_text="Identifier for the ability (e.g. 'Edge: Ghost' or 'Focus: Reroll Sneak')", max_length=255)),
                ('frequency', models.CharField(choices=[('SCENE', 'Per Scene'), ('ROUND', 'Per Round'), ('DAY', 'Per Day'), ('SESSION', 'Per Session')], max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_usages', to='characters.character')),
            ],
        ),
    ]
